export const GET_ALL_STOPS = 'GET_ALL_STOPS';
export const SET_SELECTED_STOP = 'SET_SELECTED_STOP';
export const UPDATE_USER_DONATION_DETAIL = 'UPDATE_USER_DONATION_DETAIL';
export const CHARGE_USER_FOR_DONATION = 'CHARGE_USER_FOR_DONATION';
export const UPDATE_BUS_STOP_DONATION = 'UPDATE_BUS_STOP_DONATION';
export const RESET_TRANSACTION = 'RESET_TRANSACTION';
